import React, { useState, useEffect } from 'react';
import AuthPage from './auth/AuthPage';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <body>{children}</body>
    </html> 
    </>
  )
}
